### ISSUE TITLE
Doesn't reload in dev with tailwindoutlive.css

### ISSUE THREAD

**Issue by colinaut** [kkgthb/11ty-tailwind-jit#1]
Not sure exactly what the difference is between tailwindout.css and tailwindoutlive.css but when I set it up in dev and ran dev and css:watch it did not show any tailwind css changes. I went and linked to tailwindout.css instead of tailwindoutlive.css in the html_head.liquid file and it started working.

p.s. might be nice to add [concurrently](https://github.com/kimmobrunfeldt/concurrently) to this so that you can run both dev and css:watch with a single npm script

p.p.s. Thanks for tossing this together! I was planning on messing around with tailwind jit and this was just what I was looking for!

**Comment by kkgthb** [comment]
@colinaut The difference between `tailwindout.css` and `tailwindoutlive.css` is that I had meant to delete `tailwindout.css` and the `css:...` scripts altogether from this package -- that was a copy-paste typo from previous experiments, leaving them in, that I just discovered last night and hadn't gotten around to cleaning up yet.

You **should** just have to run dev to get Tailwind to work.

That said, I wonder if you also need to force an environment variable.  I've been running it a lot with `netlify dev`, and I've got `NODE_ENV` hard-set to `production` inside of Netlify-server builds, and then `NODE_ENV` set to `development` in a `.env` file, which Netlify CLI incorporates into my build in `dev` mode.

Now that I think about it, things might be working for me because of that -- I know the Tailwind packages respond to `NODE_ENV` variable values.

**Comment by kkgthb** [comment]
@colinaut , I just uploaded a fresh commit w/ better instructions in the README about environment variables.  Try again?  _(Feel free to open a new issue if it still doesn't work!)_

**Comment by colinaut** [comment]
Ah yeah that was the issue. I went and changed the dev script in the package.json to be `"dev": "NODE_ENV=development npx eleventy --watch --serve"` to force it to run in dev. You might want to change your repo to have it the same so that it just works for others.

**Comment by kkgthb** [comment]
> You might want to change your repo to have it the same so that it just works for others.

I'd need to research how to do something that won't break builds on Windows.  :(

**Comment by colinaut** [comment]
Ah TIL that breaks Windows
